services:
  froniusd:
    image: froniusd
    container_name: froniusd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/froniusd.conf:/etc/froniusd.conf
    
    # uncomment devices for modbus rtu
    # run container as unprivileged user and 
    # group which has R/W access to the device
    #devices:
    #  - /dev/ttyUSB0
    # solarmeter:uucp
    #user: 964:987
