INSERT INTO sensors(id, mfg, model, serial, firmware, power_max) VALUES
(1, 'ABB Aurora', 'PVI-4.2-TL-OUTD', '126014', 'C.0.2.2', '4200'),
(2, 'Fronius', 'Primo', '34119102', '0.3.30.0', '4000');

INSERT INTO plan(id, payment) VALUES
(1, 0.3914);

INSERT INTO state(id, description) VALUES
(1, 'Off'),
(2, 'Sleeping (auto-shutdown)'),
(3, 'Starting up'),
(4, 'Tracking power point'),
(5, 'Forced power reduction'),
(6, 'Shutting down'),
(7, 'One or more faults exist'),
(8, 'Standby (service on unit)*might be in Events'),
(9, 'No SolarNet communication'),
(10, 'No communication with inverter'),
(11, 'Overcurrent on SolarNet plug detected'),
(12, 'Inverter is being updated'),
(13, 'AFCI Event');

INSERT INTO code(id, model, description) VALUES
(102, 'Primo', 'AC voltage too high'),
(103, 'Primo', 'AC voltage too low'),
(105, 'Primo', 'AC frequency too high'),
(106, 'Primo', 'AC frequency too low'),
(107, 'Primo', 'No AC grid detected / Wrong AC Grid State detected'),
(108, 'Primo', 'Islanding detected'),
(112, 'Primo', 'Residual Current Detected'),
(240, 'Primo', 'Arc Detected'),
(245, 'Primo', 'Arc Fault Cicruit Interrupter (AFCI) Selftest failed'),
(247, 'Primo', 'Arc Fault Cicruit Interrupter (AFCI) current sensor error'),
(249, 'Primo', 'Arc Fault Cicruit Interrupter (AFCI) detected unplausibel measurement values'),
(301, 'Primo', 'Overcurrent AC'),
(302, 'Primo', 'Overcurrent DC'),
(303, 'Primo', 'Channel 1 Overtemperature'),
(304, 'Primo', 'Channel 2 Overtemperature'),
(305, 'Primo', 'Intermediate Circuit Undervoltage'),
(306, 'Primo', 'Power Low'),
(307, 'Primo', 'DC Voltage Low'),
(308, 'Primo', 'Intermediate circuit voltage too high'),
(309, 'Primo', 'DC1 Input Overvoltage'),
(313, 'Primo', 'DC2 Input Overvoltage'),
(401, 'Primo', 'Power Stack Communication Error'),
(406, 'Primo', 'Error temperature sensor on DC board'),
(407, 'Primo', 'Error temperature sensor on AC board'),
(408, 'Primo', 'DC detected in grid'),
(412, 'Primo', 'DC1 Fix Voltage Out Of Range'),
(415, 'Primo', 'Wired Shutdown Triggered'),
(416, 'Primo', 'RECERBO - Power Stack Communication Error'),
(417, 'Primo', 'Hardware-ID Collision'),
(419, 'Primo', 'Unique ID-collision'),
(421, 'Primo', 'Hardware ID-sequence error'),
(425, 'Primo', 'Data Exchange Timeout'),
(426, 'Primo', 'Intermediate Circuit Loading Timeout'),
(427, 'Primo', 'Power Stack Ready Timeout'),
(428, 'Primo', 'Possible hardware fault'),
(431, 'Primo', 'Power Stack In Bootmode'),
(436, 'Primo', 'Invalid Bitmap Received'),
(437, 'Primo', 'Power Stack Event Handling Error'),
(438, 'Primo', 'Functional incompatibility'),
(443, 'Primo', 'DC/DC energy transfer failure'),
(445, 'Primo', 'Invalid Parameters detected'),
(447, 'Primo', 'Isolation Error'),
(450, 'Primo', 'Guard Controller - Communication Error'),
(451, 'Primo', 'Memory Check Error'),
(452, 'Primo', 'Power Stack - Filter Communication Error'),
(453, 'Primo', 'Guard Controller - AC voltage error'),
(454, 'Primo', 'Guard Controller - AC Frequency Error'),
(456, 'Primo', 'Guard Controller - Anti Islanding Selftest Error'),
(457, 'Primo', 'Grid Relay Error'),
(459, 'Primo', 'Guard Controller - Isolation Selftest Error'),
(460, 'Primo', 'Power Stack / Filter Print Reference Voltage Error'),
(461, 'Primo', 'RAM Error / Collective Fault'),
(462, 'Primo', 'Guard Controller - DC injection into grid detected'),
(463, 'Primo', 'AC Poles reversed'),
(474, 'Primo', 'Residual Current Sensor defect'),
(475, 'Primo', 'Isolation Too Low Error'),
(476, 'Primo', 'Power Stack Supply Missing'),
(482, 'Primo', 'Installation wizard aborted'),
(502, 'Primo', 'Warning - Isolation Too Low'),
(509, 'Primo', 'No Feed In For 24 Hours'),
(515, 'Primo', 'No communication with filter'),
(516, 'Primo', 'Power Stack EEPROM Error'),
(517, 'Primo', 'Power Derating Due To Overtemperature'),
(558, 'Primo', 'Incompatible Power Stack Software'),
(560, 'Primo', 'Power Derating Due To High Grid Frequency'),
(705, 'Primo', 'Solar Net - Node Type Conflict'),
(721, 'Primo', 'EEPROM - Reinitialized'),
(731, 'Primo', 'USB Flash Drive Initializing Error'),
(732, 'Primo', 'USB Flash Drive Overcurrent'),
(733, 'Primo', 'No USB Flash Drive Inserted'),
(734, 'Primo', 'No Software Update Found On USB Flash Drive'),
(735, 'Primo', 'No Supported Software Update Found On USB Flash Drive'),
(736, 'Primo', 'USB Flash Drive Flash Drive Read/Write Error'),
(738, 'Primo', 'Log-File Can\'t Be Created On The USB Flash Drive'),
(743, 'Primo', 'Software Update Failed'),
(745, 'Primo', 'Software Update Checksum Wrong'),
(751, 'Primo', 'Real Time Clock - Time Lost'),
(752, 'Primo', 'Real Time Clock - Hardware Error'),
(757, 'Primo', 'Real Time Clock - Hardware Error'),
(758, 'Primo', 'Real Time Clock - Emergency Mode'),
(766, 'Primo', 'Power Limit Not Found');

INSERT INTO code(id, model, description) VALUES
(102, 'Symo', 'AC voltage too high'),
(103, 'Symo', 'AC voltage too low'),
(105, 'Symo', 'AC frequency too high'),
(106, 'Symo', 'AC frequency too low'),
(107, 'Symo', 'No AC grid detected / Wrong AC Grid State detected'),
(108, 'Symo', 'Islanding detected'),
(112, 'Symo', 'Residual Current Detected'),
(240, 'Symo', 'Arc Detected'),
(241, 'Symo', 'Arc detection confirmation 1'),
(242, 'Symo', 'Arc detection confirmation 2'),
(245, 'Symo', 'Arc Fault Cicruit Interrupter (AFCI) Selftest failed'),
(247, 'Symo', 'Arc Fault Cicruit Interrupter (AFCI) current sensor error'),
(249, 'Symo', 'Arc Fault Cicruit Interrupter (AFCI) detected unplausibel measurement values'),
(301, 'Symo', 'Overcurrent AC'),
(302, 'Symo', 'Overcurrent DC'),
(303, 'Symo', 'Channel 1 Overtemperature'),
(306, 'Symo', 'Power Low'),
(307, 'Symo', 'DC Voltage Low'),
(308, 'Symo', 'Intermediate circuit voltage too high'),
(309, 'Symo', 'DC1 Input Overvoltage'),
(313, 'Symo', 'DC2 Input Overvoltage'),
(406, 'Symo', 'Error temperature sensor on DC board'),
(407, 'Symo', 'Error temperature sensor on AC board'),
(408, 'Symo', 'DC detected in grid'),
(412, 'Symo', 'DC1 Fix Voltage Out Of Range'),
(415, 'Symo', 'Wired Shutdown Triggered'),
(416, 'Symo', 'RECERBO - Power Stack Communication Error'),
(417, 'Symo', 'Hardware-ID Collision'),
(425, 'Symo', 'Data Exchange Timeout'),
(426, 'Symo', 'Intermediate Circuit Loading Timeout'),
(427, 'Symo', 'Power Stack Ready Timeout'),
(431, 'Symo', 'Power Stack In Bootmode'),
(432, 'Symo', 'Consistent error in power stack management'),
(433, 'Symo', 'Allocation error of dynamic addresses'),
(436, 'Symo', 'Invalid Bitmap Received'),
(437, 'Symo', 'Power Stack Event Handling Error'),
(438, 'Symo', 'Problem while error transmission from power stack to Recerbo'),
(445, 'Symo', 'Invalid Parameters detected'),
(447, 'Symo', 'Isolation Error'),
(448, 'Symo', 'No Neutral Wire'),
(450, 'Symo', 'Guard Controller - Communication Error'),
(451, 'Symo', 'Memory Check Error'),
(452, 'Symo', 'Power Stack - Filter Communication Error'),
(453, 'Symo', 'Guard Controller - AC voltage error'),
(454, 'Symo', 'Guard Controller - AC Frequency Error'),
(456, 'Symo', 'Guard Controller - Anti Islanding Selftest Error'),
(457, 'Symo', 'Grid Relay Error'),
(458, 'Symo', 'Residual Current Monitoring Unit (RCMU) Error'),
(459, 'Symo', 'Guard Controller - Isolation Selftest Error'),
(460, 'Symo', 'Power Stack / Filter Print Reference Voltage Error'),
(461, 'Symo', 'RAM Error / Collective Fault'),
(462, 'Symo', 'Guard Controller - DC injection into grid detected'),
(463, 'Symo', 'AC Poles reversed'),
(472, 'Symo', 'Ground-Fault Detector Interrupter Fuse Broken'),
(474, 'Symo', 'Residual Current Sensor defect'),
(475, 'Symo', 'Isolation Too Low Error'),
(476, 'Symo', 'Power Stack Supply Missing'),
(480, 'Symo', 'Incompatible feature'),
(481, 'Symo', 'Not supported feature'),
(482, 'Symo', 'Installation wizard aborted'),
(483, 'Symo', 'DC fix voltage out of range'),
(484, 'Symo', 'CAN transfer timeout'),
(485, 'Symo', 'CAN transmit buffer full'),
(502, 'Symo', 'Warning - Isolation Too Low'),
(509, 'Symo', 'No Feed In For 24 Hours'),
(516, 'Symo', 'Power Stack EEPROM Error'),
(517, 'Symo', 'Power Derating Due To Overtemperature'),
(519, 'Symo', 'Filter Board - EEPROM Error'),
(520, 'Symo', 'MPP Tracker #1 - No Feed In For 24 Hours'),
(521, 'Symo', 'MPP Tracker #2 - No Feed In For 24 Hours'),
(522, 'Symo', 'DC1 Input Voltage To Low'),
(523, 'Symo', 'DC2 Input Voltage Low'),
(558, 'Symo', 'Incompatible Power Stack Software'),
(559, 'Symo', 'Incompatible RECERBO Feature'),
(560, 'Symo', 'Power Derating Due To High Grid Frequency'),
(565, 'Symo', 'Arc Fault Cicruit Interrupter SD Card Error [US only]'),
(566, 'Symo', 'Arc Fault Cicruit Interrupter Deactivated Warning [US only]'),
(567, 'Symo', 'Grid Voltage Dependent Power Derating'),
(701, 'Symo', 'Solar Net - Node Type Out Of Range'),
(702, 'Symo', 'Solar Net - Receive Buffer Full'),
(703, 'Symo', 'Solar Net - Send Buffer Full'),
(705, 'Symo', 'Solar Net - Node Type Conflict'),
(706, 'Symo', 'CapKey - Get Version Failed'),
(707, 'Symo', 'CapKey - Update Failed'),
(711, 'Symo', 'EEPROM Write - Wrong Data Length'),
(712, 'Symo', 'EEPROM Write - Descriptor Not Found'),
(713, 'Symo', 'EEPROM Read - Descriptor Not Found'),
(714, 'Symo', 'EEPROM Read Warning - CRC Header Fail Will Retry'),
(715, 'Symo', 'EEPROM Read - CRC Header Fail Give It Up'),
(721, 'Symo', 'EEPROM - Reinitialized'),
(722, 'Symo', 'EEPROM - Wait Busy Timeout'),
(723, 'Symo', 'EEPROM Write - Verify Fail Will Retry'),
(724, 'Symo', 'EEPROM Write - Verify Fail Give It Up'),
(725, 'Symo', 'EEPROM Read - CRC Data Fail Will Retry'),
(726, 'Symo', 'EEPROM Read - CRC Data Fail Give It Up'),
(727, 'Symo', 'EEPROM Check Data Warning - All Data Corrupt'),
(730, 'Symo', 'EEPROM Check Data - Data Restored'),
(731, 'Symo', 'USB Flash Drive Initializing Error'),
(732, 'Symo', 'USB Flash Drive Overcurrent'),
(733, 'Symo', 'No USB Flash Drive Inserted'),
(734, 'Symo', 'No Software Update Found On USB Flash Drive'),
(735, 'Symo', 'No Supported Software Update Found On USB Flash Drive'),
(736, 'Symo', 'USB Flash Drive Flash Drive Read/Write Error'),
(737, 'Symo', 'Software Update Can Not Be Read From The USB Flash Drive'),
(738, 'Symo', 'Log-File Can\'t Be Created On The USB Flash Drive'),
(740, 'Symo', 'USB Flash Drive Enumeration Error'),
(741, 'Symo', 'USB Flash Drive Logging Write Error'),
(743, 'Symo', 'Software Update Failed'),
(745, 'Symo', 'Software Update Checksum Wrong'),
(746, 'Symo', 'Product Matrix Code (PMC) Read Error During Software Update'),
(751, 'Symo', 'Real Time Clock - Time Lost'),
(752, 'Symo', 'Real Time Clock - Hardware Error'),
(754, 'Symo', 'Real Time Clock - Time Set'),
(755, 'Symo', 'EEPROM Data Written'),
(757, 'Symo', 'Real Time Clock - Hardware Error'),
(758, 'Symo', 'Real Time Clock - Emergency Mode'),
(760, 'Symo', 'System Crystal Broken'),
(761, 'Symo', 'Device Data Unit Memory Read Error'),
(762, 'Symo', 'Plugged Device Data Unit Read Error'),
(765, 'Symo', 'Random Number Generator Error'),
(766, 'Symo', 'Power Limit Not Found'),
(767, 'Symo', 'Power Limiter Communication Error'),
(768, 'Symo', 'Power Limit Not Identical'),
(772, 'Symo', 'Memory Not Available'),
(773, 'Symo', 'Update Group Zero'),
(775, 'Symo', 'Power Stack Product Matrix Code Invalid'),
(782, 'Symo', 'Update Flash - CRC Error'),
(783, 'Symo', 'Update Flash - Header CRC Error'),
(784, 'Symo', 'Update Flash - Timeout'),
(789, 'Symo', 'Update Flash - Read Value (Header CRC Error)');

INSERT INTO code(id, model, description) VALUES
(102, 'Galvo', 'AC voltage too high'),
(103, 'Galvo', 'AC voltage too low'),
(105, 'Galvo', 'AC frequency too high'),
(106, 'Galvo', 'AC frequency too low'),
(107, 'Galvo', 'No AC grid detected / Wrong AC Grid State detected'),
(108, 'Galvo', 'Islanding detected'),
(240, 'Galvo', 'Arc Detected'),
(245, 'Galvo', 'Arc Fault Cicruit Interrupter (AFCI) Selftest failed'),
(247, 'Galvo', 'Arc Fault Cicruit Interrupter (AFCI) current sensor error'),
(249, 'Galvo', 'Arc Fault Cicruit Interrupter (AFCI) detected unplausibel measurement values'),
(301, 'Galvo', 'Overcurrent AC'),
(302, 'Galvo', 'Overcurrent DC'),
(303, 'Galvo', 'Channel 1 Overtemperature'),
(304, 'Galvo', 'Channel 2 Overtemperature'),
(306, 'Galvo', 'Power Low'),
(307, 'Galvo', 'DC Voltage Low'),
(308, 'Galvo', 'Intermediate circuit voltage too high'),
(309, 'Galvo', 'DC Input Overvoltage'),
(401, 'Galvo', 'Power Stack Communication Error'),
(406, 'Galvo', 'Error temperature sensor on DC board'),
(407, 'Galvo', 'Error temperature sensor on AC board'),
(408, 'Galvo', 'DC detected in grid'),
(412, 'Galvo', 'DC1 Fix Voltage Out Of Range'),
(415, 'Galvo', 'Wired Shutdown Triggered'),
(416, 'Galvo', 'RECERBO - Power Stack Communication Error'),
(425, 'Galvo', 'Data Exchange Timeout'),
(445, 'Galvo', 'Invalid Parameters detected'),
(452, 'Galvo', 'Power Stack - Filter Communication Error'),
(453, 'Galvo', 'Guard Controller - AC voltage error'),
(454, 'Galvo', 'Guard Controller - AC Frequency Error'),
(457, 'Galvo', 'Grid Relay Error'),
(459, 'Galvo', 'Guard Controller - Isolation Selftest Error'),
(460, 'Galvo', 'Power Stack / Filter Print Reference Voltage Error'),
(472, 'Galvo', 'Ground-Fault Detector Interrupter Fuse Broken'),
(475, 'Galvo', 'Isolation Too Low Error'),
(482, 'Galvo', 'Installation wizard aborted'),
(502, 'Galvo', 'Warning - Isolation Too Low'),
(509, 'Galvo', 'No Feed In For 24 Hours'),
(517, 'Galvo', 'Power Derating Due To Overtemperature'),
(551, 'Galvo', 'Ground Missing'),
(558, 'Galvo', 'Incompatible Power Stack Software'),
(560, 'Galvo', 'Power Derating Due To High Grid Frequency'),
(568, 'Galvo', 'Multifunction current interface Warning'),
(668, 'Galvo', 'External I/O Error'),
(721, 'Galvo', 'EEPROM - Reinitialized'),
(731, 'Galvo', 'USB Flash Drive Initializing Error'),
(732, 'Galvo', 'USB Flash Drive Overcurrent'),
(733, 'Galvo', 'No USB Flash Drive Inserted'),
(734, 'Galvo', 'No Software Update Found On USB Flash Drive'),
(735, 'Galvo', 'No Supported Software Update Found On USB Flash Drive'),
(736, 'Galvo', 'USB Flash Drive Flash Drive Read/Write Error'),
(738, 'Galvo', 'Log-File Can\'t Be Created On The USB Flash Drive'),
(743, 'Galvo', 'Software Update Failed'),
(745, 'Galvo', 'Software Update Checksum Wrong'),
(751, 'Galvo', 'Real Time Clock - Time Lost'),
(752, 'Galvo', 'Real Time Clock - Hardware Error'),
(757, 'Galvo', 'Real Time Clock - Hardware Error'),
(758, 'Galvo', 'Real Time Clock - Emergency Mode'),
(766, 'Galvo', 'Power Limit Not Found');

INSERT INTO code(id, model, description) VALUES
(102, 'IGPlus', 'AC voltage too high'),
(103, 'IGPlus', 'AC voltage too low'),
(105, 'IGPlus', 'AC frequency too high'),
(106, 'IGPlus', 'AC frequency too low'),
(107, 'IGPlus', 'No AC grid detected'),
(108, 'IGPlus', 'Islanding detected'),
(109, 'IGPlus', 'General mains error'),
(112, 'IGPlus', 'AC voltage too high Phase 1'),
(113, 'IGPlus', 'AC voltage too low Phase 1'),
(115, 'IGPlus', 'AC frequency too high Phase 1'),
(116, 'IGPlus', 'AC frequency too low Phase 1'),
(117, 'IGPlus', 'No AC grid detected Phase 1'),
(122, 'IGPlus', 'AC voltage too high Phase 2'),
(123, 'IGPlus', 'AC voltage too low Phase 2'),
(125, 'IGPlus', 'AC frequency too high Phase 2'),
(126, 'IGPlus', 'AC frequency too low Phase 2'),
(127, 'IGPlus', 'No AC grid detected Phase 2'),
(132, 'IGPlus', 'AC voltage too high Phase 3'),
(133, 'IGPlus', 'AC voltage too low Phase 3'),
(135, 'IGPlus', 'AC frequency too high Phase 3'),
(136, 'IGPlus', 'AC frequency too low Phase 3'),
(137, 'IGPlus', 'No AC grid detected Phase 3'),
(207, 'IGPlus', 'General mains error'),
(208, 'IGPlus', 'Jumper Test Failed'),
(240, 'IGPlus', 'Arc detected'),
(245, 'IGPlus', 'Arc Blocker (PV-AFCI-NL board) self test failed'),
(247, 'IGPlus', 'Arc Blocker (PV-AFCI-NL board) current sensor error'),
(248, 'IGPlus', 'Arc Blocker (PV-AFCI-NL board) Jumper Test Failed'),
(249, 'IGPlus', 'Arc Blocker (PV-AFCI-NL board) damaged'),
(250, 'IGPlus', 'NO ERROR - Manual test of Arc Blocker (PV-AFCI-NL board) successful'),
(301, 'IGPlus', 'Overcurrent AC'),
(302, 'IGPlus', 'Overcurrent DC'),
(303, 'IGPlus', 'Overtemperature PINCI board'),
(304, 'IGPlus', 'Overtemperature Heat sink'),
(305, 'IGPlus', 'Energytransfer not possible'),
(306, 'IGPlus', 'Power Low'),
(307, 'IGPlus', 'DC Low'),
(308, 'IGPlus', 'Intermediate circuit voltage too high'),
(401, 'IGPlus', 'Communication error between IG BRAIN and PINCI board'),
(402, 'IGPlus', 'Write access to the internal memory failed'),
(403, 'IGPlus', 'Internal memory with country settings incomplete'),
(406, 'IGPlus', 'Temperature sensor PINCI board faulty'),
(407, 'IGPlus', 'Temperature sensor heat sink faulty or not connected'),
(408, 'IGPlus', 'DC injection'),
(412, 'IGPlus', 'DC voltage too high'),
(413, 'IGPlus', 'DC voltage too high'),
(414, 'IGPlus', 'Memory array for Fronius IG Plus type in EEPROM faulty'),
(416, 'IGPlus', 'Communication error between IG BRAIN and power stack'),
(417, 'IGPlus', 'Hardware ID-collision'),
(419, 'IGPlus', 'Unique ID-collision'),
(421, 'IGPlus', 'Hardware ID-sequence error'),
(425, 'IGPlus', 'Receive timeout for data exchange with one or more power stacks exceeded'),
(431, 'IGPlus', 'All PINCI boards are in boot mode'),
(439, 'IGPlus', 'Disconnection of one PINCI board because of a problem on another PINCI board (in Balance Mode)'),
(442, 'IGPlus', 'Master for one phase could not be assigned'),
(443, 'IGPlus', 'DC/DC energy transfer failure'),
(445, 'IGPlus', 'Wrong power stack configuration'),
(450, 'IGPlus', 'Guard Detection - Monitoring of the central processing unit is active'),
(451, 'IGPlus', 'Guard Memory problem'),
(452, 'IGPlus', 'Guard communication problem'),
(453, 'IGPlus', 'Guard AC voltage failure detected'),
(454, 'IGPlus', 'Guard AC frequency failure detected'),
(455, 'IGPlus', 'Guard AC failure detected'),
(456, 'IGPlus', 'Guard anti islanding test failure detected'),
(457, 'IGPlus', 'Guard mains relays stuck'),
(460, 'IGPlus', 'Referencevoltage outside permitted limits'),
(461, 'IGPlus', 'Internal memory (RAM) consitency check failure'),
(464, 'IGPlus', 'Display version incompatible'),
(465, 'IGPlus', 'Display version unkown'),
(466, 'IGPlus', 'Display not available'),
(467, 'IGPlus', 'Timeout during start up'),
(469, 'IGPlus', 'Output inductor connection mixed up'),
(470, 'IGPlus', 'Buck converter relay doesn't open'),
(471, 'IGPlus', 'Module grounding fuse defective'),
(472, 'IGPlus', 'Grounding Fuse defect'),
(474, 'IGPlus', '100kOhm module grounding measurement detects failure'),
(475, 'IGPlus', 'DC isolation failure'),
(476, 'IGPlus', 'Arc Blocker Communication Fail'),
(477, 'IGPlus', 'Arc Blocker Communication has stopped'),
(478, 'IGPlus', 'Arc Blocker Manual Test failed'),
(502, 'IGPlus', 'DC isolation failure'),
(504, 'IGPlus', 'Solar Net address conflict'),
(505, 'IGPlus', 'Internal memory with country settings incomplete'),
(506, 'IGPlus', 'Internal memory with TOTAL values incomplete'),
(507, 'IGPlus', 'Internal memory with DAY/YEAR values incomplete'),
(508, 'IGPlus', 'Internal memory for IG Number is incomplete'),
(509, 'IGPlus', 'No feed in operation for 24 hours'),
(510, 'IGPlus', 'Errors detected by Solar Net self diagnostic system'),
(511, 'IGPlus', 'Errors detected by Solar Net Sensor Card self diagnostic system'),
(512, 'IGPlus', 'According to the device type too many PINCI boards have been detected'),
(513, 'IGPlus', 'PINCI boards in boot mode'),
(514, 'IGPlus', 'According to the device type not enough PINCI boards have been detected'),
(515, 'IGPlus', 'One or more PINCI boards with State Codes (406/407/409/410)'),
(516, 'IGPlus', 'One PINCI board exceeds the permitted limit of error messages per day'),
(517, 'IGPlus', 'Permanent Power Low or DC Low error'),
(550, 'IGPlus', 'String fuse defective'),
(551, 'IGPlus', 'Grounding Fuse defective'),
(553, 'IGPlus', 'Communication problem with one phasemaster'),
(558, 'IGPlus', 'Feature disabled'),
(559, 'IGPlus', 'Low Voltage Ride Through (LVRT) active'),
(560, 'IGPlus', 'Grid Frequency-dependent Power Reduction (GFPR) active'),
(561, 'IGPlus', 'Power reduction because of over temperature');





