{
 "title": "Solarmeter",
 "description": "Show data from a smart energy meter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "year",
    "query": "SELECT extract(year FROM time) AS year FROM yearly_view ORDER BY time DESC LIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Energy $year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  energy_sum AS energy\nFROM\n  yearly_view\nORDER BY\n  time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Energy $year Trend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  energy_percent\nFROM get_solar_trend()"
    }
   ]
  },
  {
   "title": "AC Feed-in Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT                                                   \n  time,\n  ac_power_w\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Daily Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  energy\nFROM daily_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  time,\n  credit\nFROM daily_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Credit $year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  credit\nFROM\n  yearly_view\nORDER BY\n  time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Energy Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  current_date as time,\n  last(ac_energy, time) - first(ac_energy, time) as energy_today\nFROM live\nWHERE\n  time > current_date"
    }
   ]
  },
  {
   "title": "DC Power Tracker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  AVG(dc_power_1) OVER(ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS String1,\n  AVG(dc_power_2) OVER(ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS String2\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Monthly Energy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  energy_sum\nFROM monthly_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  time,\n  credit\nFROM monthly_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_5m AS time,\n  pwr_w AS power\nFROM cagg_power\nWHERE\n  $__timeFilter(bucket_5m)\nORDER BY 1"
    }
   ]
  }
 ]
}